#%RAML 1.0
title: batch-template
description: A standard way of implementing batch processing and capture failure and successful records
baseUri: http://localhost:8081/batch-processing/

/batch:
  /run:
    get:
      description: Run batch job
      responses:
        200:
          body:
            application/json:
              
  /status:
    get:
      description: Get the status of batch
      responses:
        200:
          body:
            application/json:
  
    delete:
       description: Clear current object store status
       responses:
         200:
          body:
            application/json:
                         
/failure:
    get:
      description: Get all failed records
      responses:
        200:
          body:
            application/json:
              
/data:
    get:
      description: Provide sample records for testing
      responses:
        200:
          body:
            application/csv:
            
/healthcheck:
  get:
    responses:
      200:
        body:
          application/json: